version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - 9200:9200
    healthcheck:
      test: curl -s http://elasticsearch:9200 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 30
    networks:
      - sfnetwork
    # volumes:
    #   - ./elasticsearch/data:/usr/share/elasticsearch/data
    #   - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  books-service:
    image: books-service
    container_name: ms-books-service
    build:
      context: ./ms-books
      dockerfile: ./Dockerfile
    ports:
      - 3500:8080
    networks:
      - sfnetwork
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - MS_BOOKS_PORT=8080
      - EUREKA_URL=http://eurekaserver:8761/eureka
    depends_on:
      elasticsearch:
        condition: service_healthy
  writer-service:
    image: writer-service
    container_name: ms-writer-service
    build:
      context: ./ms-writer
      dockerfile: ./Dockerfile
    ports:
      - 3000:8080
    networks:
      - sfnetwork
    environment:
      # - ELASTICSEARCH_URL=http://elasticsearch:9200
      - MS_WRITER_PORT=8080
      - EUREKA_URL=http://eurekaserver:8761/eureka
  eurekaserver:
    image: eurekaserver
    container_name: eurekaserver
    build:
      context: ./eurekaserver
      dockerfile: ./Dockerfile
    ports:
      - 8761:8761
    networks:
      - sfnetwork
    environment:
      - EUREKA_SERVER_PORT=8761
networks:
  sfnetwork:
    driver: bridge