services:
  mysqldatabase:
    image: mysql:8.2
    container_name: mysqldatabase
    ports:
      - 3306:3306
    networks:
      - sfnetwork
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 15s
      timeout: 10s
      retries: 12
    volumes:
      - mysql_data:/var/lib/mysql
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - 9200:9200
    healthcheck:
      test: curl -s http://elasticsearch:9200 >/dev/null || exit 1
      interval: 15s
      timeout: 10s
      retries: 12
    networks:
      - sfnetwork
  books-service:
    image: books-service
    container_name: ms-books-service
    build:
      context: ./ms-books
      dockerfile: ./Dockerfile
    ports:
      - 3500:8080
    networks:
      - sfnetwork
    environment:
      - ELASTICSEARCH_URL=$ELASTICSEARCH_URL
      - MS_BOOKS_PORT=8080
      - EUREKA_URL=$EUREKA_URL
    depends_on:
      elasticsearch:
        condition: service_healthy
  writer-service:
    image: writer-service
    container_name: ms-writer-service
    build:
      context: ./ms-writer
      dockerfile: ./Dockerfile
    ports:
      - 3000:8080
    networks:
      - sfnetwork
    environment:
      - MS_WRITER_PORT=8080
      - EUREKA_URL=$EUREKA_URL
      - MYSQL_HOST=$MYSQL_HOST
      - MYSQL_PORT=$MYSQL_PORT
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - EUREKA_MS_BOOKS_URL=$EUREKA_MS_BOOKS_URL
    depends_on:
      mysqldatabase:
        condition: service_healthy
  eurekaserver:
    image: eurekaserver
    container_name: eurekaserver
    build:
      context: ./eurekaserver
      dockerfile: ./Dockerfile
    ports:
      - 8761:8761
    networks:
      - sfnetwork
    environment:
      - EUREKA_SERVER_PORT=8761
  api-gateway:
    image: api-gateway
    container_name: api-gateway
    build:
      context: ./cloud-gateway
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    networks:
      - sfnetwork
    environment:
      - EUREKA_URL=$EUREKA_URL
networks:
  sfnetwork:
    driver: bridge
volumes:
  mysql_data: