### Get all items from the wishlist
GET http://localhost:8080/ms-writer/api/wish-list/items

### Add a new item to the wishlist
POST http://localhost:8080/ms-writer/api/wish-list/items/47e1ca10-3c2a-4909-9891-04551b68cdcd