### Get all items from the wishlist
GET http://localhost:8080/ms-writer/api/wishlist/items

### Add a new item to the wishlist
POST http://localhost:8080/ms-writer/api/wishlist/items/25e2ca09-47c4-437b-a3aa-955b97372143